name: CI Pipeline

on:
  push:
    branches:
      - main
      - '**'
  pull_request:

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Flake8 linter with output configuration
      - name: Run Flake8
        run: |
          flake8 src/ --output-file=flake8-report.txt || true
          cat flake8-report.txt

<<<<<<< HEAD
      # Step 5: Run Pytest
      - name: Run Pytest
        run: |
          pytest --cov=src tests/  # Runs tests and measures code coverage
=======
>>>>>>> a80c535059f131ff6e8097e5f62a9b50577e850c
